# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9TyXRErATHVUtIBCWLM7onG0B5N-pNA
"""

import numpy as np
import pandas as pd
import pickle
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tải mô hình và công cụ xử lý
model = load_model("model/lstm_model.h5")
with open("model/tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)
with open("model/scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

# Tải dữ liệu giá sản phẩm
df_gia = pd.read_csv("data/gia_san_pham.csv")

def predict_total(text_input):
    seq = tokenizer.texts_to_sequences([text_input])
    seq_pad = pad_sequences(seq, maxlen=30)
    y_pred = model.predict(seq_pad)[0][0]  # đầu ra là 1 số
    return scaler.inverse_transform([[y_pred]])[0][0]  # trả về giá trị tiền thật

def split_expense(total, muc_song):
    if muc_song == "Tiết kiệm":
        weights = {
            "Gạo": 0.18, "Thịt": 0.16, "Rau": 0.1, "Cá": 0.12,
            "Điện": 0.08, "Nước": 0.05, "Thuê nhà": 0.22, "Khác": 0.09
        }
    elif muc_song == "Vừa đủ":
        weights = {
            "Gạo": 0.16, "Thịt": 0.18, "Rau": 0.1, "Cá": 0.13,
            "Điện": 0.1, "Nước": 0.06, "Thuê nhà": 0.2, "Khác": 0.07
        }
    else:  # Dư giả
        weights = {
            "Gạo": 0.14, "Thịt": 0.2, "Rau": 0.1, "Cá": 0.15,
            "Điện": 0.12, "Nước": 0.07, "Thuê nhà": 0.17, "Khác": 0.05
        }
    result = {k: round(total * v, 2) for k, v in weights.items()}
    return result